export const cropTypes = [
  'Maize',
  'Tomato',
  'Cabbage',
  'Onion',
  'Mango',
  'Banana',
  'Pineapple',
  'Carrot',
  'Capsicum',
  'Eggplant',
  'Sukuma Wiki',
  'Spinach',
  'Beans',
  'Garlic',
  'Strawberry',
  'Lettuce',
  'Cucumber',
  'Watermelon',
  'Pumpkin',
  'Passion Fruit'
];

export const cropThresholds: Record<string, number> = {
  'Maize': 35,
  'Tomato': 45,
  'Cabbage': 55,
  'Onion': 40,
  'Mango': 35,
  'Banana': 60,
  'Pineapple': 40,
  'Carrot': 50,
  'Capsicum': 45,
  'Eggplant': 50,
  'Sukuma Wiki': 55,
  'Spinach': 55,
  'Beans': 40,
  'Garlic': 40,
  'Strawberry': 50,
  'Lettuce': 55,
  'Cucumber': 50,
  'Watermelon': 40,
  'Pumpkin': 45,
  'Passion Fruit': 45
};